/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

	mcdonalds("[restaurant][mcdonalds]",1500),
    montaditos("[restaurant][montaditos]",1500),
    UNIVERSIDADE("[place][UNIVERSIDADE]",1500),
	FORUM("[place][FORUM]",1500),
	GLICINIAS("[place][GLICINIAS]",1500),
	SIM("[action][SIM]",1500),
	NAO("[action][NAO]",1500),
	RECUAR("[action][RECUAR]",1500),
	AVANCAR("[action][AVANCAR]",1500),;

private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
