/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

	/*montaditos("[restaurant][montaditos]",3000),
    UNIVERSIDADE("[place][UNIVERSIDADE]",3000),
	FORUM("[place][FORUM]",3000),
	GLICINIAS("[place][GLICINIAS]",3000),
	*/
	SIM("[][][][][][][][sim]",3000),
	NAO("[][][][][][][][nao]",3000),
	RECUAR("[][return][][][][][][]",3000),
	AVANCAR("[][avancar][][][][][][]",3000),
	RAPIDO("[][rapido][][][][][][]",3000),
	DEVAGAR("[][devagar][][][][][][]",3000),;

private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
